<?php print_php_header() ?>

namespace <?php echo $namespace ?>;

/**
 * THIS FILE IS GENERATED BY THE DATA MODEL BUILDER
 * DO NOT EDIT THIS FILE MANUALLY. IT WILL BE OVERWRITTEN 
 * NEXT TIME YOUR RUN THE DATA MDEL GENERATOR
 */
class DateTimeConversion {

    const SETTINGS = <?php echo $settings?>;

}
